### ISSUE TITLE
ModuleNotFoundError: No module named 'ksuid'

### ISSUE THREAD

**Issue by kevinggrimm** [svix/python-ksuid#22]
I resolved this, though sharing in case anyone runs into a similar issue. The error could absolutely be due to an unconventional configuration of `pip` on my system or old pip installation:

### To recreate
```bash
pip3 install svix-ksuid
python3
```
Throws `ModuleNotFoundError`
```python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ksuid import Ksuid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ksuid'
```

### Resolution: Use `python3 -m pip` to install
```bash
pip3 uninstall svix-ksuid -y
python3 -m pip install svix-ksuid 
python3
```
Now works as intended
```python
>>> from ksuid import Ksuid
>>> 
```

### Update
I later ran into a second issue where, upon attempting to call a python script, the module could not be found:
```bash
<name_of_python_module> <command>
....
....
....
    from ksuid import Ksuid
ModuleNotFoundError: No module named 'ksuid'
```

Turns out that I needed to run the installation into the Python installation that my code was referencing using the `--target` argument. The script ran fine after this
```bash
which python3
# /usr/local/bin/python3
pip3 install --target /usr/local/lib/python3.7/site-packages/ --upgrade svix-ksuid
```

**Comment by tasn** [comment]
It really sounds like something in your python environment. FWIW `python3 -m pip` is fine, but it should be identical to `pip3` (when the latter exists).

Are you using `virtualenv`, `pipenv` or global installation? I suspect it may be the latter due to the updated comment. Are you using the default python3 on macOS, or did you install it from brew? The reason why I'm asking is because mac has a default python, and the homebrew one would be different so it could be that you're installing with one and testing with another.

That's why using a `virtualenv` is often the best idea btw. :P

**Comment by kevinggrimm** [comment]
Yup, that was it. I was not using a `virtualenv` (and will be sure to default to that approach now!) and my initial installation was global for the default macOS. I did install a different Python version some time ago, so maybe it's time to revisit that...

Thanks for the reply, much appreciated!

**Comment by tasn** [comment]
With pleasure, and glad we got it sorted! 💪🏻 

Closing the ticket as it's now solved.
