### ISSUE TITLE
Improve performance by using the Rust implementation

### ISSUE THREAD

**Issue by ericbn** [svix/python-ksuid#26]
Hi 👋

First thanks for the great package. Adding the `KsuidMs` variant (40 timestamp + 120 random bits) is great as it kind of gives the best of the two UUIDv4 (122 random bits) and ULID (48 timestamp + 80 random bits) worlds!

Since you also maintain https://github.com/svix/rust-ksuid, have you considered using the Rust implementation with Python to further [improve the performance](https://github.com/timonwong/cyksuid/blob/master/README.md#benchmark) of the Python package and even reduce the amount of code to maintain? (Never did this before, but looks like [PyO3](https://github.com/PyO3/pyo3) or [rust-cpython](https://github.com/dgrunwald/rust-cpython) are among the preferred tools for the task)

**Comment by tasn** [comment]
We've considered it (and I've done it before in other libraries I maintain), though decided not to, at least for now.

I don't think this performance difference will be a bottleneck for more users of this library, but on the other hand, having a package that's Python only means that it can just be installed in every environment without having to compile it first, which is a big win (and is a big pain otherwise).

**Comment by ericbn** [comment]
Cool, thanks for the heads up and the thoughtful considerations! I'll close this.

**Comment by tasn** [comment]
Thanks for the suggestion, and please let us know if you have any other ideas!
